services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql # Asegurar que init.sql está disponible

volumes:
  database_data:
